//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace webAPI.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class lr_base_role
    {
        public string F_RoleId { get; set; }
        public string F_Category { get; set; }
        public string F_EnCode { get; set; }
        public string F_FullName { get; set; }
        public Nullable<int> F_SortCode { get; set; }
        public Nullable<int> F_DeleteMark { get; set; }
        public Nullable<int> F_EnabledMark { get; set; }
        public string F_Description { get; set; }
        public Nullable<System.DateTime> F_CreateDate { get; set; }
        public string F_CreateUserId { get; set; }
        public string F_CreateUserName { get; set; }
        public Nullable<System.DateTime> F_ModifyDate { get; set; }
        public string F_ModifyUserId { get; set; }
        public string F_ModifyUserName { get; set; }
    }
}
