//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace webAPI.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HYDatabaseEntities : DbContext
    {
        public HYDatabaseEntities()
            : base("name=HYDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<lr_base_company> lr_base_company { get; set; }
        public virtual DbSet<lr_base_department> lr_base_department { get; set; }
        public virtual DbSet<lr_base_log> lr_base_log { get; set; }
        public virtual DbSet<lr_base_post> lr_base_post { get; set; }
        public virtual DbSet<lr_base_role> lr_base_role { get; set; }
        public virtual DbSet<lr_base_user> lr_base_user { get; set; }
    }
}
