//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi_EmployeeInformationEntry.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hy_Recruit_CardInfo
    {
        public Nullable<int> F_EnabledMark { get; set; }
        public string F_CreateUserId { get; set; }
        public string F_ModifyUserName { get; set; }
        public string F_ModifyUserId { get; set; }
        public Nullable<int> F_DeleteMark { get; set; }
        public Nullable<int> F_SortCode { get; set; }
        public Nullable<System.DateTime> F_ModifyDate { get; set; }
        public string F_CreateUserName { get; set; }
        public Nullable<System.DateTime> F_CreateDate { get; set; }
        public string F_Description { get; set; }
        public string F_ID { get; set; }
        public string F_Name { get; set; }
        public string F_Sex { get; set; }
        public string F_Birthday { get; set; }
        public string F_Address { get; set; }
        public string F_CardID { get; set; }
        public string F_IssueOrgan { get; set; }
        public string F_ValidStart { get; set; }
        public string F_ValidEnd { get; set; }
        public string F_SexCode { get; set; }
        public string F_AppendMsg { get; set; }
        public string F_PhotoBase64 { get; set; }
        public string F_PhotoBase64_F { get; set; }
        public string photoBase64_ZF { get; set; }
        public string strIDUID { get; set; }
    }
}
