//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaoQinAndHRDataBasicsWService.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class pub_user
    {
        public string user_uid { get; set; }
        public string login_name { get; set; }
        public string user_code { get; set; }
        public string password { get; set; }
        public Nullable<byte> user_type { get; set; }
        public string user_name { get; set; }
        public string dept_uid { get; set; }
        public string third_part_code { get; set; }
        public Nullable<byte> sex { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public Nullable<System.DateTime> join_date { get; set; }
        public Nullable<System.DateTime> fire_date { get; set; }
        public string zjhm { get; set; }
        public string zjdz { get; set; }
        public string lxdz { get; set; }
        public Nullable<byte> xueli { get; set; }
        public string mobiletelephone { get; set; }
        public string email { get; set; }
        public string telephone { get; set; }
        public Nullable<byte> user_status { get; set; }
        public Nullable<byte> hunkuan { get; set; }
        public Nullable<byte> jiguan { get; set; }
        public string remarks { get; set; }
        public Nullable<System.DateTime> create_time { get; set; }
        public string kq_fangan_code { get; set; }
        public Nullable<byte> kq_rpt { get; set; }
        public string kq_bc { get; set; }
        public string creater { get; set; }
        public string allow_ip_arrange { get; set; }
        public string zhiwu { get; set; }
        public Nullable<byte> leibie { get; set; }
        public string zhiji { get; set; }
        public string gangwei { get; set; }
        public Nullable<byte> mz { get; set; }
        public string group_uid { get; set; }
        public Nullable<int> sqcz_code { get; set; }
        public Nullable<int> sqcz_pass { get; set; }
        public Nullable<System.DateTime> Ena_date { get; set; }
        public int user_serial { get; set; }
        public string Cost_center { get; set; }
        public string user_name_en { get; set; }
        public Nullable<System.DateTime> go_work_date { get; set; }
        public Nullable<System.DateTime> last_ats { get; set; }
        public Nullable<byte> last_direction { get; set; }
        public string cb_uid { get; set; }
        public string nj_uid { get; set; }
        public string bj_uid { get; set; }
        public string qsfz_uid { get; set; }
        public Nullable<byte> enable_tx { get; set; }
        public Nullable<System.DateTime> date_bx_begin { get; set; }
        public Nullable<System.DateTime> date_zzrq { get; set; }
        public Nullable<System.DateTime> date_txrq { get; set; }
        public Nullable<System.DateTime> date_bx_end { get; set; }
        public Nullable<System.DateTime> date_ht_begin { get; set; }
        public Nullable<System.DateTime> date_ht_end { get; set; }
        public string address_home { get; set; }
        public string info_110 { get; set; }
        public Nullable<byte> guoji { get; set; }
        public string jiguan2 { get; set; }
        public string language { get; set; }
        public Nullable<byte> employ_type { get; set; }
        public string Location_code { get; set; }
        public Nullable<byte> user_source { get; set; }
        public Nullable<byte> Degree { get; set; }
        public Nullable<byte> zjlx { get; set; }
        public string graduate_school { get; set; }
        public Nullable<System.DateTime> graduate_date { get; set; }
        public Nullable<byte> political_landscape { get; set; }
        public string specialty { get; set; }
        public string user_zh { get; set; }
        public string bankname { get; set; }
        public string user_ybkh { get; set; }
        public string user_gjjkh { get; set; }
        public string user_ylbxkh { get; set; }
        public string comp_id { get; set; }
        public string ext_phone { get; set; }
        public Nullable<byte> is_bybus { get; set; }
        public string bus_line { get; set; }
        public Nullable<byte> user_grade { get; set; }
        public string trial_period { get; set; }
        public Nullable<byte> healthy_type { get; set; }
        public string pre_working_age { get; set; }
        public string direct_manager { get; set; }
        public Nullable<byte> is_initpwd { get; set; }
        public string src_user_code { get; set; }
        public string user_def1 { get; set; }
        public string user_def2 { get; set; }
        public string user_def3 { get; set; }
        public string user_def4 { get; set; }
        public string user_def5 { get; set; }
        public string user_def6 { get; set; }
        public string user_def7 { get; set; }
        public string user_def8 { get; set; }
        public string user_def9 { get; set; }
        public string user_def10 { get; set; }
        public string sap_id { get; set; }
        public string kq_place { get; set; }
        public string user_def11 { get; set; }
        public string user_def12 { get; set; }
        public string user_def13 { get; set; }
        public string user_def14 { get; set; }
        public string user_def15 { get; set; }
        public string user_def16 { get; set; }
        public string user_def17 { get; set; }
        public string user_def18 { get; set; }
        public string user_def19 { get; set; }
        public string user_def20 { get; set; }
        public string user_jbdhfa_uid { get; set; }
        public Nullable<byte> user_valid_status { get; set; }
        public Nullable<byte> user_is_wp { get; set; }
        public Nullable<byte> user_dataflag { get; set; }
        public Nullable<System.DateTime> user_export_time { get; set; }
        public string user_secondpwd { get; set; }
        public Nullable<int> user_login_validcount { get; set; }
        public Nullable<int> user_login_status { get; set; }
        public Nullable<System.DateTime> user_login_time { get; set; }
        public string user_mgr_pwd { get; set; }
        public Nullable<byte> user_phase { get; set; }
        public Nullable<byte> user_is_flow { get; set; }
        public Nullable<int> user_approve_status { get; set; }
        public Nullable<System.DateTime> user_approve_date { get; set; }
        public string user_approver { get; set; }
        public string phone_store_uid { get; set; }
        public string user_photo_uid { get; set; }
        public string user_weixin { get; set; }
        public string user_dingding { get; set; }
        public string user_weixin_openid { get; set; }
        public string user_global_code { get; set; }
        public string incorp_comp { get; set; }
    }
}
