//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi_EmployeeInformationEntry.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hy_Recruit_InterviewQuestionBank
    {
        public Nullable<int> F_EnabledMark { get; set; }
        public string F_CreateUserId { get; set; }
        public string F_ModifyUserName { get; set; }
        public string F_ModifyUserId { get; set; }
        public Nullable<int> F_DeleteMark { get; set; }
        public Nullable<int> F_SortCode { get; set; }
        public Nullable<System.DateTime> F_ModifyDate { get; set; }
        public string F_CreateUserName { get; set; }
        public Nullable<System.DateTime> F_CreateDate { get; set; }
        public Nullable<int> F_Description { get; set; }
        public string F_ID { get; set; }
        public string F_Question { get; set; }
        public string F_Answer { get; set; }
        public string F_Fraction { get; set; }
    }
}
