//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi_EmployeeInformationEntry.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hy_Recruit_ProcessOperation
    {
        public string ID { get; set; }
        public string SubProcessId { get; set; }
        public int OperationStatus { get; set; }
        public string Remark { get; set; }
        public string OperationContent { get; set; }
        public string CandidatesId { get; set; }
        public Nullable<System.DateTime> OperationTime { get; set; }
        public string Operator { get; set; }
    
        public virtual Hy_Recruit_Candidates Hy_Recruit_Candidates { get; set; }
    }
}
