//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi_EmployeeInformationEntry.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class lr_base_company
    {
        public string F_CompanyId { get; set; }
        public Nullable<int> F_Category { get; set; }
        public string F_ParentId { get; set; }
        public string F_EnCode { get; set; }
        public string F_ShortName { get; set; }
        public string F_FullName { get; set; }
        public string F_Nature { get; set; }
        public string F_OuterPhone { get; set; }
        public string F_InnerPhone { get; set; }
        public string F_Fax { get; set; }
        public string F_Postalcode { get; set; }
        public string F_Email { get; set; }
        public string F_Manager { get; set; }
        public string F_ProvinceId { get; set; }
        public string F_CityId { get; set; }
        public string F_CountyId { get; set; }
        public string F_Address { get; set; }
        public string F_WebAddress { get; set; }
        public Nullable<System.DateTime> F_FoundedTime { get; set; }
        public string F_BusinessScope { get; set; }
        public Nullable<int> F_SortCode { get; set; }
        public Nullable<int> F_DeleteMark { get; set; }
        public Nullable<int> F_EnabledMark { get; set; }
        public string F_Description { get; set; }
        public Nullable<System.DateTime> F_CreateDate { get; set; }
        public string F_CreateUserId { get; set; }
        public string F_CreateUserName { get; set; }
        public Nullable<System.DateTime> F_ModifyDate { get; set; }
        public string F_ModifyUserId { get; set; }
        public string F_ModifyUserName { get; set; }
    }
}
