//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi_EmployeeInformationEntry.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class lr_base_user
    {
        public string F_UserId { get; set; }
        public string F_EnCode { get; set; }
        public string F_Account { get; set; }
        public string F_Password { get; set; }
        public string F_Secretkey { get; set; }
        public string F_RealName { get; set; }
        public string F_NickName { get; set; }
        public string F_HeadIcon { get; set; }
        public string F_QuickQuery { get; set; }
        public string F_SimpleSpelling { get; set; }
        public Nullable<int> F_Gender { get; set; }
        public Nullable<System.DateTime> F_Birthday { get; set; }
        public string F_Mobile { get; set; }
        public string F_Telephone { get; set; }
        public string F_Email { get; set; }
        public string F_OICQ { get; set; }
        public string F_WeChat { get; set; }
        public string F_MSN { get; set; }
        public string F_CompanyId { get; set; }
        public string F_DepartmentId { get; set; }
        public Nullable<int> F_SecurityLevel { get; set; }
        public Nullable<int> F_OpenId { get; set; }
        public string F_Question { get; set; }
        public string F_AnswerQuestion { get; set; }
        public Nullable<int> F_CheckOnLine { get; set; }
        public Nullable<System.DateTime> F_AllowStartTime { get; set; }
        public Nullable<System.DateTime> F_AllowEndTime { get; set; }
        public Nullable<System.DateTime> F_LockStartDate { get; set; }
        public Nullable<System.DateTime> F_LockEndDate { get; set; }
        public Nullable<int> F_SortCode { get; set; }
        public Nullable<int> F_DeleteMark { get; set; }
        public Nullable<int> F_EnabledMark { get; set; }
        public string F_Description { get; set; }
        public Nullable<System.DateTime> F_CreateDate { get; set; }
        public string F_CreateUserId { get; set; }
        public string F_CreateUserName { get; set; }
        public Nullable<System.DateTime> F_ModifyDate { get; set; }
        public string F_ModifyUserId { get; set; }
        public string F_ModifyUserName { get; set; }
        public string F_IDCard { get; set; }
        public string F_PrimaryOrganization { get; set; }
        public string F_SecondaryOrganization { get; set; }
        public string F_TertiaryOrganization { get; set; }
        public string F_FourLevelOrganization { get; set; }
        public string F_FiveLevelOrganization { get; set; }
        public string F_SixLevelOrganization { get; set; }
        public string F_RecruitmentChannels { get; set; }
        public Nullable<System.DateTime> F_Entrydate { get; set; }
        public Nullable<System.DateTime> F_ConfirmationDate { get; set; }
        public Nullable<System.DateTime> F_DepartureDate { get; set; }
        public string F_Education { get; set; }
        public string F_SalaryMethod { get; set; }
        public string F_PayModel { get; set; }
        public string F_WorkingSystem { get; set; }
        public string F_BankCardNumber { get; set; }
        public string F_BankDeposit { get; set; }
        public Nullable<System.DateTime> F_DateHoldingPost { get; set; }
        public Nullable<int> F_IsTrainingAgreement { get; set; }
        public Nullable<System.DateTime> F_StartDateService { get; set; }
        public Nullable<System.DateTime> F_EndDateService { get; set; }
        public string F_EmployeeNature { get; set; }
        public Nullable<System.DateTime> F_EmployeeNatureChangeDate { get; set; }
        public string F_PieceworkType { get; set; }
        public Nullable<System.DateTime> F_TimeBecomeRegular { get; set; }
        public Nullable<System.DateTime> F_TimeShiftWorkSystem { get; set; }
        public string F_TypesResignation { get; set; }
        public Nullable<System.DateTime> F_MakeUpTime { get; set; }
        public string F_PostId { get; set; }
        public string F_SalaryCalculation { get; set; }
        public Nullable<int> F_Age { get; set; }
        public string F_DocumentType { get; set; }
        public string F_NationAlity { get; set; }
        public string F_Nation { get; set; }
        public string F_RRNature { get; set; }
        public string F_PoliticalOutlook { get; set; }
        public string F_MaritalStatus { get; set; }
        public string F_NativePlace { get; set; }
        public string F_OnJobStatus { get; set; }
        public Nullable<System.DateTime> F_IDCardStartDate { get; set; }
        public Nullable<System.DateTime> F_IDCardEndDate { get; set; }
        public string F_OneCardNumber { get; set; }
        public string F_SalaryStructureType { get; set; }
        public string F_SalaryType { get; set; }
        public string F_PersonnelCategory { get; set; }
        public Nullable<System.DateTime> F_JoiningGroupDate { get; set; }
        public string F_EntryChannel { get; set; }
        public string F_OfflineDate { get; set; }
        public string F_InternalCode { get; set; }
        public string F_InternalName { get; set; }
        public string F_InternalCompany { get; set; }
        public Nullable<System.DateTime> F_LaborRecruitmentDate { get; set; }
        public string F_RecruitmentCompany { get; set; }
        public string F_GraduationUniversitie { get; set; }
        public string F_MajorStudied { get; set; }
        public Nullable<System.DateTime> F_EducationStartDate { get; set; }
        public Nullable<System.DateTime> F_EducationEndDate { get; set; }
        public string F_EducationalMode { get; set; }
        public string F_ForeignLanguageLevel { get; set; }
        public Nullable<int> F_IsQualified { get; set; }
        public string F_QualificationName { get; set; }
        public string F_GetTime { get; set; }
        public string F_InternalTitleType { get; set; }
        public string F_InternalTitle { get; set; }
        public Nullable<System.DateTime> F_InternalTitleDate { get; set; }
        public string F_SocialTitleType { get; set; }
        public string F_SocialTitle { get; set; }
        public Nullable<System.DateTime> F_SocialTitleDate { get; set; }
        public string F_IDCardAddress { get; set; }
        public string F_PermanentAddress { get; set; }
        public string F_ResidentialAddress { get; set; }
        public string F_CurrentAddress { get; set; }
        public string F_EmergencyContact { get; set; }
        public string F_EContactRelationship { get; set; }
        public string F_EContactNumber { get; set; }
        public string F_ContactAddress { get; set; }
        public Nullable<System.DateTime> F_laborContractStartDate { get; set; }
        public Nullable<System.DateTime> F_laborContractEndDate { get; set; }
        public string F_LaborContractStatus { get; set; }
        public Nullable<System.DateTime> F_AttendanceDeadline { get; set; }
        public string F_IsEsignationCertificate { get; set; }
        public string F_Depreciation { get; set; }
        public string F_UserState { get; set; }
    }
}
